DEBUG_NONE=const(0)         # No debugging settings are enabled
DEBUG_COROUTINES=const(1)   # Output responsiveness of the coroutine loop
DEBUG_THREADS=const(2)      # Output response times of control loop thread
DEBUG_ADC=const(4)          # Output ADC values
DEBUG_ADC_SIMULATE=const(8) # Simulate ADC values for testing
DEBUG_EVENT_LOG=const(16)   # Output event logs
DEBUG_ACTIVITY_LOG=const(32)# Output activity logs
DEBUG_WEB_REQUEST=const(64) # Output the web requests
DEBUG_PRESSURE_CHANGE=const(128) # Debug monitoring of pressure changes
